enum actionTypes {
  AUTH_START = "AUTH_START",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_ERROR = "AUTH_ERROR",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_FINISH = "AUTH_FINISH",
  CLEAR_ERROR = "CLEAR_ERROR",
  PHRASE_START = "PHRASE_START",
  PHRASE_SUCCESS = "PHRASE_SUCCESS",
  PHRASE_CLEAR = "PHRASE_CLEAR",
  PHRASE_ACTION = "PHRASE_ACTION",
  PHRASE_ERROR = "PHRASE_ERROR",
  PHRASE_CLEAR_ERROR = "PHRASE_CLEAR_ERROR",
  PHRASE_ADD_NEW_SUCCESS = "PHRASE_ADD_NEW_SUCCESS",
  PHRASE_INCREMENT_SUCCESS = "PHRASE_INCREMENT_SUCCESS",
  PHRASE_INCREMENT_START = "PHRASE_INCREMENT_START",
  USER_START = "USER_START",
  USER_SUCCESS = "USER_SUCCESS",
  USER_FOLLOW_HANDLER = "USER_FOLLOW_HANDLER",
}

export default actionTypes;
